# Generated by Django 4.2.6 on 2023-10-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appt1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='Usuario',
        ),
    ]
