# Generated by Django 4.2.6 on 2023-10-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt1', '0003_alter_usuario_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.TextField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.TextField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ddi',
            field=models.TextField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.TextField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.TextField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.TextField(default='SOME STRING', max_length=255),
        ),
    ]
