# Generated by Django 4.2.6 on 2023-10-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt1', '0004_usuario_celular_usuario_cpf_usuario_ddi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sobrenome',
            field=models.TextField(default='SOME STRING', max_length=255),
        ),
    ]
