# Generated by Django 4.2.6 on 2023-10-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt1', '0005_usuario_sobrenome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emaill', models.TextField(max_length=255)),
                ('senhal', models.TextField(max_length=255)),
            ],
        ),
    ]
