# Generated by Django 4.2.6 on 2023-11-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appt1", "0007_esenha"),
    ]

    operations = [
        migrations.CreateModel(
            name="cria_gauge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emaill", models.TextField(max_length=255)),
                ("senhal", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="cria_grafico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emaill", models.TextField(max_length=255)),
                ("senhal", models.TextField(max_length=255)),
            ],
        ),
    ]
