# Generated by Django 4.2.6 on 2023-11-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt1', '0008_cria_gauge_cria_grafico'),
    ]

    operations = [
        migrations.CreateModel(
            name='novos_valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.TextField(default='SOME STRING', max_length=255)),
                ('hum', models.TextField(default='SOME STRING', max_length=255)),
                ('luz', models.TextField(default='SOME STRING', max_length=255)),
                ('press', models.TextField(default='SOME STRING', max_length=255)),
                ('gas', models.TextField(default='SOME STRING', max_length=255)),
                ('rpm', models.TextField(default='SOME STRING', max_length=255)),
                ('vento', models.TextField(default='SOME STRING', max_length=255)),
                ('ar', models.TextField(default='SOME STRING', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='cria_gauge',
        ),
        migrations.DeleteModel(
            name='cria_grafico',
        ),
    ]
