# Generated by Django 4.2.6 on 2024-06-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt1', '0010_rgraficos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
